nodes:
  indexer:
    name: wazuh-indexer
    ip: [wazuh-indexer, 127.0.0.1]
  manager:
    name: wazuh-manager
    ip: [wazuh-manager, 127.0.0.1]
  dashboard:
    name: wazuh-dashboard
    ip: [wazuh-dashboard, 127.0.0.1]