version: "3.9"

# --- Swarm Networks ---
networks:
  edge:
    name: edge
    driver: overlay
    attachable: true

# --- Swarm Volumes ---
volumes:
  portainer_data:
    name: portainer_data
    external: true
  pihole_data:
    name: pihole_data
    driver: local

# --- Secrets ---
secrets:
  cloudflare_tunnel_token:
    external: true

# ============================================================================
# Services
# ============================================================================

services:

  # --------------------------------------------------------------------------
  # CLOUDFLARED (Tunnel Endpoint)
  # --------------------------------------------------------------------------
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run --token /run/secrets/cloudflare_tunnel_token
    networks:
      - edge
    environment:
      - TZ=${TZ}
    secrets:
      - source: cloudflare_tunnel_token
        target: cloudflare_tunnel_token
    deploy:
      mode: replicated
      replicas: 1

  # --------------------------------------------------------------------------
  # TRAEFIK (Reverse Proxy and Entrypoint)
  # --------------------------------------------------------------------------
  traefik:
    image: traefik:v3.1
    restart: on-failure
    networks:
      - edge
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=edge
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.docker.network=edge
        - 'traefik.http.routers.traefik.rule=Host(`traefik.silentgarden.org`)'
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal

  # --------------------------------------------------------------------------
  # PORTAINER (Swarm Management UI)
  # --------------------------------------------------------------------------
  portainer:
    image: portainer/portainer-ce:latest
    restart: on-failure
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=edge
        - 'traefik.http.routers.portainer.rule=Host(`portainer.silentgarden.org`)'
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000

  # --------------------------------------------------------------------------
  # PIHOLE (DNS + Web UI)
  # --------------------------------------------------------------------------
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - edge
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_PASSWORD}   # set your password in .env
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - pihole_data:/etc/pihole
      - pihole_data:/etc/dnsmasq.d
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: ingress
      - target: 53
        published: 53
        protocol: udp
        mode: ingress
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=edge
        - 'traefik.http.routers.pihole.rule=Host(`pihole.silentgarden.org`)'
        - traefik.http.routers.pihole.entrypoints=web
        - traefik.http.services.pihole.loadbalancer.server.port=80
