version: "3.9"

# --- Swarm Networks ---
# Overlay network is required for multi-host communication and the Traefik routing mesh
networks:
  edge:
    name: core_edge
    driver: overlay
    attachable: true

# --- Swarm Volumes ---
# External is used for persistent data that should exist beyond the stack lifecycle
volumes:
  portainer_data:
    name: portainer_data
    external: true # Assumes you will create this volume manually or it already exists

# --- Secrets ---
# It's best practice to use Swarm Secrets for sensitive data like tokens
secrets:
  cloudflare_tunnel_token:
    external: true # Assumes you will create this secret manually

# --- Services (The Containers) ---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run --token /run/secrets/cloudflare_tunnel_token
    networks:
      - edge
    environment:
      - TZ=${TZ}
    secrets:
      - source: cloudflare_tunnel_token
        target: cloudflare_tunnel_token
    deploy:
      mode: replicated
      replicas: 1

  traefik:
    image: traefik:v3.1
    restart: on-failure
    networks:
      - edge
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # FIX APPLIED: Removed the deprecated --providers.docker.swarmmode=true
      - --providers.docker.network=core_edge
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    # Traefik labels for Swarm must be inside the `deploy` block
    deploy:
      mode: global
      labels:
        # Traefik Dashboard exposure
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.silentgarden.org`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal

  portainer:
    image: portainer/portainer-ce:latest
    restart: on-failure
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    # Traefik labels for Swarm must be inside the `deploy` block
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.silentgarden.org`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000