version: "3.9"

# --- Swarm Networks ---
# Overlay network is required for multi-host communication and the Traefik routing mesh
networks:
  edge:
    name: edge
    driver: overlay
    attachable: true

# --- Swarm Volumes ---
# External is used for persistent data that should exist beyond the stack lifecycle
volumes:
  portainer_data:
    name: portainer_data
    external: true # Assumes you will create this volume manually or it already exists

# --- Secrets ---
# It's best practice to use Swarm Secrets for sensitive data like tokens
secrets:
  cloudflare_tunnel_token:
    external: true # Assumes you will create this secret manually

# --- Services (The Containers) ---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run --token /run/secrets/cloudflare_tunnel_token
    networks:
      - edge
    environment:
      - TZ=${TZ}
    secrets:
      - source: cloudflare_tunnel_token
        target: cloudflare_tunnel_token
    deploy:
      mode: replicated
      replicas: 1

  traefik:
    image: traefik:v3.1
    restart: on-failure
    networks:
      - edge
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # FIX APPLIED: Removed the deprecated --providers.docker.swarmmode=true
      - --providers.docker.network=core_edge
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    # Traefik labels for Swarm must be inside the `deploy` block
    deploy:
      mode: global
      labels:
        # Traefik Dashboard exposure
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.silentgarden.org`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal

  pihole:
    image: pihole/pihole:latest
    # Pi-hole must be deployed as a global service to guarantee it runs on the manager node (your Mac)
    # where the ports are published.
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

    environment:
      TZ: ${TZ:-America/New_York}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-changeme}
      DNS1: ${PIHOLE_DNS1:-1.1.1.1}
      DNS2: ${PIHOLE_DNS2:-1.0.0.1}
      # The IP address must be set here when not using host mode
      PIHOLE_INTERFACE: eth0
      # Ensure ports are exposed for Traefik and DNS
      VIRTUAL_HOST: pihole.silentgarden.org
      # The rest of the setup relies on Traefik for port 80/443

    volumes:
      - "${BASE_PATH}/config/pihole/etc-pihole:/etc/pihole"
      - "${BASE_PATH}/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "${BASE_PATH}/config/pihole/logs:/var/log/pihole"

    # --- Network and Port Configuration ---

    # 1. Manually publish DNS port (53)
    # This must be done manually because Traefik doesn't handle UDP/TCP on 53 well.
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host

    # 2. Add Traefik labels for the Web UI (Port 80)
    labels:
      - "traefik.enable=true"
      # Router for HTTP (Port 80) - we assume Traefik redirects HTTP to HTTPS
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`pihole.silentgarden.org`)"
      # Service definition
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

    # 3. Connect to an overlay network for Traefik to access it
    networks:
      - edge

  portainer:
    image: portainer/portainer-ce:latest
    restart: on-failure
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    # Traefik labels for Swarm must be inside the `deploy` block
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.silentgarden.org`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000