version: "3.9"

# --- Swarm Networks ---
networks:
  # The overlay network for all service communication
  edge:
    name: edge
    driver: overlay
    attachable: true

# --- Swarm Volumes ---
volumes:
  portainer_data:
    name: portainer_data
    external: true

# --- Secrets ---
secrets:
  cloudflare_tunnel_token:
    external: true

# ============================================================================
# Services
# ============================================================================

services:

  # --------------------------------------------------------------------------
  # CLOUDFLARED (Tunnel Endpoint)
  # --------------------------------------------------------------------------
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run --token /run/secrets/cloudflare_tunnel_token
    networks:
      - edge
    environment:
      - TZ=${TZ}
    secrets:
      - source: cloudflare_tunnel_token
        target: cloudflare_tunnel_token
    deploy:
      mode: replicated
      replicas: 1

  # --------------------------------------------------------------------------
  # TRAEFIK (Reverse Proxy and Entrypoint)
  # --------------------------------------------------------------------------
  traefik:
    image: traefik:v3.1
    restart: on-failure
    networks:
      - edge
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=edge
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # CRITICAL: Host mode for entrypoints 80/443 (only 80 used here)
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      # Traefik Dashboard port
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      labels:
        # Traefik Dashboard exposure
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.silentgarden.org`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal

  # --------------------------------------------------------------------------
  # PIHOLE (DNS and Web Interface)
  # --------------------------------------------------------------------------
  pihole:
    image: pihole/pihole:latest
    deploy:
      # For DNS, pihole needs to run on the node where ports 53 are available.
      mode: global
      restart_policy:
        condition: on-failure

    environment:
      TZ: ${TZ:-America/New_York}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-changeme}
      DNS1: ${PIHOLE_DNS1:-1.1.1.1}
      DNS2: ${PIHOLE_DNS2:-1.0.0.1}
      # Required for correct Pi-hole networking inside Docker
      PIHOLE_INTERFACE: eth0
      # Required for the web interface to work correctly with Traefik
      FTLCONF_LOCAL_IPV4: 192.168.10.133 # Use your intended Host IP
      # We rely on Traefik for web routing, so no VIRTUAL_HOST/PORT needed.

    volumes:
      - "${BASE_PATH}/config/pihole/etc-pihole:/etc/pihole"
      - "${BASE_PATH}/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "${BASE_PATH}/config/pihole/logs:/var/log/pihole"

    # CRITICAL: Manually publish DNS ports 53/tcp and 53/udp in host mode
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host

    # Traefik labels for the Pi-hole Web UI (Port 80 internally)
    labels:
      - "traefik.enable=true"
      # Router for HTTP
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`pihole.silentgarden.org`)"
      # Service definition (internal port 80)
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

    # Connect to the overlay network
    networks:
      - edge

  # --------------------------------------------------------------------------
  # PORTAINER (Swarm Management UI)
  # --------------------------------------------------------------------------
  portainer:
    image: portainer/portainer-ce:latest
    restart: on-failure
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.silentgarden.org`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000