version: "3.9"

# --- Swarm Networks ---
networks:
  # The overlay network for all service communication
  edge:
    name: edge
    driver: overlay
    attachable: true

# --- Swarm Volumes ---
volumes:
  portainer_data:
    name: portainer_data
    external: true

# --- Secrets ---
secrets:
  cloudflare_tunnel_token:
    external: true

# ============================================================================
# Services
# ============================================================================

services:

  # --------------------------------------------------------------------------
  # CLOUDFLARED (Tunnel Endpoint)
  # --------------------------------------------------------------------------
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure
    command: tunnel --no-autoupdate run --token /run/secrets/cloudflare_tunnel_token
    networks:
      - edge
    environment:
      - TZ=${TZ}
    secrets:
      - source: cloudflare_tunnel_token
        target: cloudflare_tunnel_token
    deploy:
      mode: replicated
      replicas: 1

  # --------------------------------------------------------------------------
  # TRAEFIK (Reverse Proxy and Entrypoint)
  # --------------------------------------------------------------------------
  traefik:
    image: traefik:v3.1
    restart: on-failure
    networks:
      - edge
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # FIX 1: Traefik must point to the *name* of the network it's connected to.
      - --providers.docker.network=edge
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # FIX 2: Traefik requires Host mode ports for the entrypoints (80, 443)
      # when running as a global service to guarantee traffic reaches it on every node.
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      # Traefik Dashboard port, for monitoring/API access
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: global # Ensures Traefik runs on all nodes
      labels:
        # Traefik Dashboard exposure (using internal service)
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.silentgarden.org`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal

  # --------------------------------------------------------------------------
  # PIHOLE (DNS and Web Interface)
  # --------------------------------------------------------------------------
  pihole:
    image: pihole/pihole:latest
    # Pi-hole should generally be deployed on a specific node or as a single replica.
    # We keep 'global' as you specified, but it's only truly functional where the ports are open.
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

    environment:
      TZ: ${TZ:-America/New_York}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-changeme}
      DNS1: ${PIHOLE_DNS1:-1.1.1.1}
      DNS2: ${PIHOLE_DNS2:-1.0.0.1}
      # FIX 3: PIHOLE_INTERFACE must be set to 'eth0' for bridge/overlay networking.
      PIHOLE_INTERFACE: eth0
      # FIX 4: Set the correct environment variable for the internal IP address.
      # This is crucial to avoid the 404 error when Traefik forwards the request.
      FTLCONF_LOCAL_IPV4: 192.168.10.133 # Use your intended Host IP here.
      # Removed VIRTUAL_HOST and other web-related ENV vars as Traefik handles routing.

    volumes:
      - "${BASE_PATH}/config/pihole/etc-pihole:/etc/pihole"
      - "${BASE_PATH}/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "${BASE_PATH}/config/pihole/logs:/var/log/pihole"

    # 1. Manually publish DNS port (53)
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host

    # 2. Add Traefik labels for the Web UI (Port 80)
    labels:
      - "traefik.enable=true"
      # Router for HTTP
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`pihole.silentgarden.org`)"
      # Service definition
      # FIX 5: Use the correct internal port for Pi-hole's web interface (it's 80).
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # FIX 6: Add a path prefix for the Pi-hole web UI. This is critical for the 404 fix.
      - "traefik.http.routers.pihole.middlewares=pihole-strip@docker"
      - "traefik.http.middlewares.pihole-strip.stripprefix.prefixes=/admin"

    # 3. Connect to the overlay network
    networks:
      - edge

  # --------------------------------------------------------------------------
  # PORTAINER (Swarm Management UI)
  # --------------------------------------------------------------------------
  portainer:
    image: portainer/portainer-ce:latest
    restart: on-failure
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.silentgarden.org`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000