version: "3.9"

services:
  db:
    image: postgres:16
    container_name: nc-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nextcloud}
      POSTGRES_USER: ${POSTGRES_USER:-nextcloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}
    volumes:
      - /Volumes/Office/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nextcloud} -d ${POSTGRES_DB:-nextcloud}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nc-redis
    command: ["redis-server", "--appendonly", "yes"]
    # If you set REDIS_PASSWORD, uncomment next line:
    # command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - /Volumes/Office/redis:/data
    restart: unless-stopped

  app:
    image: nextcloud:29-apache
    container_name: nextcloud
    depends_on:
      - db
      - redis
    ports:
      - "${NEXTCLOUD_HTTP_PORT:-8080}:80"
    environment:
      # Database connection
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB:-nextcloud}
      POSTGRES_USER: ${POSTGRES_USER:-nextcloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}

      # Redis cache (Nextcloud auto-wires this into config.php)
      REDIS_HOST: redis
      # REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}   # if you enabled requirepass above

      # General
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS:-localhost}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT:-10G}
      TZ: ${TZ:-UTC}
    volumes:
      # Keep app code, config, and data separate and persistent
      - /Volumes/Office/html:/var/www/html
      - /Volumes/Office/apps:/var/www/html/custom_apps
      - /Volumes/Office/config:/var/www/html/config
      - /Volumes/Office/data:/var/www/html/data
    restart: unless-stopped

# Remove named volumes since they're no longer needed
volumes: {}