services:
  db:
    image: mariadb:10.11
    container_name: seafile-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?set in .env}
      # Seafile will create/populate these on first run
      MYSQL_LOG_CONSOLE: "true"
    volumes:
      - /Volumes/Office/seafile/db:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD:?set in .env} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - seafile
    restart: unless-stopped

  memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    command: ["-m", "${MEMCACHED_MEMORY_MB:-256}"]
    healthcheck:
      test: ["CMD-SHELL", 'printf "version\r\n" | nc -w 2 127.0.0.1 11211 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - seafile
    restart: unless-stopped

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_healthy
    ports:
      - "8081:80"        # Web UI (change host port if you need)
      # - "8082:8082"    # Optional: file server direct port if you expose it separately
    environment:
      DB_HOST: db
      DB_ROOT_PASSWD: ${MYSQL_ROOT_PASSWORD:?set in .env}

      # General
      SEAFILE_SERVER_HOSTNAME: ${SEAFILE_SERVER_HOSTNAME:-localhost}
      SEAFILE_ADMIN_EMAIL: ${SEAFILE_ADMIN_EMAIL:-admin@example.com}
      SEAFILE_ADMIN_PASSWORD: ${SEAFILE_ADMIN_PASSWORD:?set in .env}
      TIME_ZONE: ${TZ:-UTC}

      # Optional tuning
      SEAFILE_SERVER_LETSENCRYPT: "false"   # Use your reverse proxy/TLS termination
      ENABLE_JSON_LOG: "true"
    volumes:
      # Seafile image expects a single shared dir; it will structure subdirs under /shared
      - /Volumes/Office/seafile/data:/shared
      - /Volumes/Office/seafile/logs:/var/log/seafile
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
    networks:
      - seafile
    restart: unless-stopped

networks:
  seafile:
    driver: bridge
