volumes:
  nc_apps:
    driver: local
    driver_opts: { type: none, o: bind, device: /Volumes/Office/apps }
  nc_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /Volumes/Office/config }
  nc_data:
    driver: local
    driver_opts: { type: none, o: bind, device: /Volumes/Office/data }
  db_data:
    driver: local
    driver_opts: { type: none, o: bind, device: /Volumes/Office/db }
  redis_data:
    driver: local
    driver_opts: { type: none, o: bind, device: /Volumes/Office/redis }
  php_conf:
    driver: local
    driver_opts: { type: none, o: bind, device: /Volumes/Office/php-conf }  # holds opcache.ini

services:
  db:
    image: postgres:16
    container_name: nc-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nextcloud}
      POSTGRES_USER: ${POSTGRES_USER:-nextcloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nextcloud} -d ${POSTGRES_DB:-nextcloud}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - nextcloud
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nc-redis
    # If you set REDIS_PASSWORD, uncomment and use the second command:
    command: ["redis-server", "--appendonly", "yes"]
    # command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6380}:6379"
    networks:
      - nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:29-apache
    container_name: nextcloud
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      - nextcloud
    environment:
      # Database connection
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB:-nextcloud}
      POSTGRES_USER: ${POSTGRES_USER:-nextcloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}

      # Redis cache (Nextcloud will wire this into config.php)
      REDIS_HOST: redis
      # REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}

      # General
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS:-localhost}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-1024M}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT:-10G}
      TZ: ${TZ:-UTC}
    volumes:
      # Persist everything on the portable drive
      - nc_apps:/var/www/html/custom_apps
      - nc_config:/var/www/html/config
      - nc_data:/var/www/html/data

      # Drop-in PHP/OPcache tuning (file created below)
      - php_conf:/usr/local/etc/php/conf.d
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(extension_loaded(\"apcu\") ? 0 : 1);'"]
      interval: 30s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # Real cron so background jobs don’t slow page loads
  cron:
    image: nextcloud:29-apache
    container_name: nc-cron
    entrypoint: /cron.sh
    depends_on:
      - app
    networks:
      - nextcloud
    volumes:
      - nc_apps:/var/www/html/custom_apps
      - nc_config:/var/www/html/config
      - nc_data:/var/www/html/data
      - php_conf:/usr/local/etc/php/conf.d
    restart: unless-stopped

networks:
  nextcloud:
    driver: bridge
