version: "3.9"
services:
  write-certs-yml:
    image: alpine:3.20
    command: /bin/sh -c 'printf "%s" "$CERTS_YML_B64" | base64 -d > /config/certs.yml'
    environment:
      # base64 of your certs.yml content (paste via Portainer env var)
      - CERTS_YML_B64=
    volumes:
      - wazuh_config:/config
    restart: "no"

  gen-certs:
    image: wazuh/wazuh-certs-generator:0.0.2
    depends_on: [write-certs-yml]
    volumes:
      - wazuh_certs:/certificates
      - wazuh_config:/config
    restart: "no"

volumes:
  wazuh_certs:
  wazuh_config:
