services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    # uncomment if you need an HTTP proxy during generation
    # environment:
    #   - HTTP_PROXY=http://<YOUR_PROXY_ADDRESS_OR_DNS>
