version: "3.9"

# ============================================================================
# Swarm Configuration: Secrets and Networks
# ============================================================================
secrets:
  # Secrets must be created externally before deployment (e.g., via Portainer or CLI)
  vpn_service_provider:
    external: true
  vpn_type:
    external: true
  wireguard_private_key:
    external: true
  wireguard_addresses:
    external: true
  wireguard_endpoint:
    external: true
  wireguard_public_key:
    external: true
  dns:
    external: true

# Networks - 'edge' is external, 'vpn_internal' and 'default' are created by the stack
networks:
  # 1. Internal VPN network (for services to communicate privately)
  vpn_internal:
    driver: overlay
    attachable: true
  # 2. External Traefik/Cloudflare network (assumes you have a Traefik setup)
  edge:
    external: true
    name: core_edge # Assumes this Swarm network is already created
  # 3. Default internal network for the stack (used by tdarr-node)
  default:
    driver: overlay
    attachable: true

# ============================================================================
# Services
# ============================================================================
services:
  # ==========================================================================
  # VPN Gateway - ALL Traefik routing will point to this service.
  # ==========================================================================
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      # Non-sensitive variables loaded from .env
      - TZ=${TZ}
    # Secrets are used instead of environment variables for credentials
    secrets:
      - vpn_service_provider
      - vpn_type
      - wireguard_private_key
      - wireguard_addresses
      - wireguard_endpoint
      - wireguard_public_key
      - dns
    volumes:
      - "${BASE_PATH}/gluetun:/gluetun"
    networks:
      - vpn_internal # Internal VPN network for download clients
      - edge         # External Traefik network
    # Traefik labels must be inside the 'deploy' block in Swarm mode
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Traefik routing configuration (Labels point to Gluetun's internal IP)
        - traefik.enable=true
        - traefik.docker.network=core_edge # Crucial: Specifies the network Traefik should use for routing

        # qBittorrent (Target port 8282 on Gluetun)
        - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.silentgarden.org`)
        - traefik.http.routers.qbittorrent.entrypoints=web
        - traefik.http.services.qbittorrent.loadbalancer.server.port=8282

        # Prowlarr (Target port 9696 on Gluetun)
        - traefik.http.routers.prowlarr.rule=Host(`prowlarr.silentgarden.org`)
        - traefik.http.routers.prowlarr.entrypoints=web
        - traefik.http.services.prowlarr.loadbalancer.server.port=9696

        # Sonarr (Target port 8989 on Gluetun)
        - traefik.http.routers.sonarr.rule=Host(`sonarr.silentgarden.org`)
        - traefik.http.routers.sonarr.entrypoints=web
        - traefik.http.services.sonarr.loadbalancer.server.port=8989

        # Radarr (Target port 7878 on Gluetun)
        - traefik.http.routers.radarr.rule=Host(`radarr.silentgarden.org`)
        - traefik.http.routers.radarr.entrypoints=web
        - traefik.http.services.radarr.loadbalancer.server.port=7878

        # Lidarr (Target port 8686 on Gluetun)
        - traefik.http.routers.lidarr.rule=Host(`lidarr.silentgarden.org`)
        - traefik.http.routers.lidarr.entrypoints=web
        - traefik.http.services.lidarr.loadbalancer.server.port=8686

        # NZBGet (Target port 6789 on Gluetun)
        - traefik.http.routers.nzbget.rule=Host(`nzbget.silentgarden.org`)
        - traefik.http.routers.nzbget.entrypoints=web
        - traefik.http.services.nzbget.loadbalancer.server.port=6789

        # Slskd (Target port 5030 on Gluetun)
        - traefik.http.routers.slskd.rule=Host(`slskd.silentgarden.org`)
        - traefik.http.routers.slskd.entrypoints=web
        - traefik.http.services.slskd.loadbalancer.server.port=5030

        # Soularr (Target port 5000 on Gluetun)
        - traefik.http.routers.soularr.rule=Host(`soularr.silentgarden.org`)
        - traefik.http.routers.soularr.entrypoints=web
        - traefik.http.services.soularr.loadbalancer.server.port=5000
    restart: unless-stopped

  # ==========================================================================
  # Download Clients (VPN Protected)
  # ==========================================================================

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    networks:
      - vpn_internal # Connect to the internal VPN network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8282
    volumes:
      - "${BASE_PATH}/config/qbittorrent:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - gluetun.bind=true
    restart: unless-stopped

  # --- NZBGet ---
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    depends_on:
      - gluetun
    networks:
      - vpn_internal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NZBGET_PORT=6789
    volumes:
      - "${BASE_PATH}/config/nzbget:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  # --- Slskd ---
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    depends_on:
      - gluetun
    networks:
      - vpn_internal
    environment:
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - "${BASE_PATH}/config/slskd:/app"
      - "${BASE_PATH}/media/downloads/slsk:/downloads"
      - "${BASE_PATH}/media/downloads/slsk/incomplete:/incomplete"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  # --- Prowlarr ---
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - gluetun
    networks:
      - vpn_internal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BASE_PATH}/config/prowlarr:/config"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  # --- Sonarr ---
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - gluetun
      - prowlarr
    networks:
      - vpn_internal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BASE_PATH}/config/sonarr:/config"
      - "${BASE_PATH}/media/tv-shows:/data/tvshows"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  # --- Radarr ---
  radarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: radarr
    depends_on:
      - gluetun
      - prowlarr
    networks:
      - vpn_internal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BASE_PATH}/config/radarr:/config"
      - "${BASE_PATH}/media/movies:/data/movies"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  # --- Lidarr ---
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    depends_on:
      - gluetun
      - prowlarr
    networks:
      - vpn_internal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - "${BASE_PATH}/config/lidarr:/config"
      - "${BASE_PATH}/media/music:/data/music"
      - "${BASE_PATH}/media/downloads:/downloads"
      - "${BASE_PATH}/media/downloads/slsk:/download/slsk"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  # --- Soularr ---
  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    depends_on:
      - gluetun
      - lidarr
      - slskd
    networks:
      - vpn_internal
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
      - SCRIPT_INTERVAL=300
    volumes:
      - "${BASE_PATH}/config/soularr